version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres 
      postgres_user: hyper 
      postgres_pass: ${PG_PW} 
      postgres_db: hyper-graph-node 
      postgres_port: 5432
      ipfs: 'ipfs:5001'
      ethereum: 'testnet:${ETH_RPC}'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - /home/ubuntu/graph/data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: hyper 
      POSTGRES_PASSWORD: ${PG_PW} 
      POSTGRES_DB: hyper-graph-node 
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - /home/ubuntu/graph/data/postgres:/var/lib/postgresql/data
